### ISSUE TITLE
Test Rococo parachain

### ISSUE THREAD

**Issue by thanhtung6824** [polkafoundry/newpolka#10]
Now Rococo validators and Polkafoundry node have fully deployed on AWS Server but it not yet tested with the actual Rococo relay chain.
We need to run our own Parachains testnet locally to make sure it's set up correctly.

Create a docker-compose file follow the instruction below in order to test

# Launch the Relay Chain
## Generate a raw chain spec
`./target/release/polkadot build-spec --chain rococo-local --disable-default-bootnode --raw > rococo-local.json
`
### Alice
`docker run -d -p 9944:9944 -p 9933:9933 rococo --alice --chain rococo-local.json  --unsafe-rpc-external --rpc-cors all --unsafe-ws-external --rpc-methods=Unsafe  --discover-local
`
### Bob
`docker run -d -p 8844:9944 -p 8833:9933 -p 30330:30333 rococo --bob --chain rococo-local.json --unsafe-rpc-external --rpc-cors all --unsafe-ws-external --rpc-methods=Unsafe  --discover-local
`
### Validator
`docker run -d -p 7744:9944 -p 7733:9933 -p 30331:30333 rococo --validator --chain rococo-local.json --name polkafoundry_rococo1 --unsafe-rpc-external --rpc-cors all --unsafe-ws-external --rpc-methods=Unsafe  --discover-local
`
# Launch the ParaChain
## Export genesis state
`./target/release/polkafoundry export-genesis-state --parachain-id 14 > genesis-state
`
## Export genesis wasm
`./target/release/polkafoundry export-genesis-wasm > genesis-wasm
`
### Collator
`docker run -d -p 5544:9944 -p 5533:9933 -p 20336:30333 halongbay --collator --parachain-id 14  --discover-local -- --execution wasm --chain ../polkadot/rococo-local.json --port 30335  --discover-local
`
### Full Node
`docker run -d -p 4444:9944 -p 4433:9933 -p 20337:30333 halongbay --parachain-id 14  --discover-local -- --execution wasm --chain ../polkadot/rococo-local.json --port 30337  --discover-local
`

**Comment by birick888** [comment]
https://github.com/polkafoundry/newpolka/commit/35575effcea6e742d720d13cf51cae4a314e76f4

**Comment by thanhtung6824** [comment]
It's not yet done, please don't close it

**Comment by thanhtung6824** [comment]
![image](https://user-images.githubusercontent.com/28278313/111769093-5af2a980-88db-11eb-81a1-44acb19e2aa8.png)
It seems to work correctly. The Parachain starting to import new blocks.

**Comment by thanhtung6824** [comment]
https://twitter.com/PolkaFoundry/status/1377512511533109249
